;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Data.APCost",DevComment="")
+GameplayTagList=(Tag="Data.Damage",DevComment="")
+GameplayTagList=(Tag="Data.Debuff.Bleed",DevComment="")
+GameplayTagList=(Tag="Data.Debuff.Vulnerable",DevComment="")
+GameplayTagList=(Tag="Data.ManaCost",DevComment="")
+GameplayTagList=(Tag="Event.PlayTargetCard",DevComment="")
+GameplayTagList=(Tag="Identity.Enemy",DevComment="")
+GameplayTagList=(Tag="Identity.Player",DevComment="")
+GameplayTagList=(Tag="State.Buff.BaicAttackDmgBonus",DevComment="")
+GameplayTagList=(Tag="State.Buff.BasicAttackMult",DevComment="")
+GameplayTagList=(Tag="State.Buff.DefHandSizeBonus",DevComment="")
+GameplayTagList=(Tag="State.Buff.DmgMitigationBonus",DevComment="")
+GameplayTagList=(Tag="State.Debuff.Bleed",DevComment="")
+GameplayTagList=(Tag="State.Debuff.Vulnerable",DevComment="")
+GameplayTagList=(Tag="State.Defense.Block",DevComment="")
+GameplayTagList=(Tag="State.Defense.Dodge",DevComment="")
+GameplayTagList=(Tag="State.Defense.Parry",DevComment="")

